Remove `ContactMap` (allowing rename `ContactFrequency` => `ContactMap`)
dwhswenson/contact_map pull request #88
Opened 2020-09-04 12:00 UTC by dwhswenson

This is the next step in #82. Removes `ContactMap` and adds `PendingDeprecationWarning` on `ContactFrequency`.

This also bumps the version to 0.7.0.dev0 (which should have been done as soon as we broke the API in #87; changed API means we're developing on the next 0.x).

2020-09-05 13:39 UTC, sroet requested changes
Only a comment about combining strings without `+` inside brackets, for cleaner indentation.

LGTM otherwise

2020-09-05 13:39 UTC, sroet commented on contact_map/contact_map.py
> +        + "more, see https://github.com/dwhswenson/contact_map/issues/82"
plusses are not needed inside brackets
```suggestion
        "Invoking it as ContactFrequency will be deprecated in 0.8. For "
        "more, see https://github.com/dwhswenson/contact_map/issues/82"
```
Lead to better indentation (in my opinion)

2020-09-23 17:10 UTC, dwhswenson commented
Desired changes are done ... I had completely forgotten that this was still sitting here!

2020-09-23 17:36 UTC, sroet approved these changes
LGTM, feel free to merge

2020-09-23 17:57 UTC, merged

2020-09-23 17:59 UTC, dwhswenson commented
Update #82 to reflect current status.